my_file = open('my_f.txt', 'r')
content = my_file.read()
print(f'Содержимое файла, текст: \n {content}')
my_file = open('my_f.txt', 'r')
content = my_file.readlines()
print(f'Количество строк в файле - {len(content)}')
my_file = open('my_f.txt', 'r')
content = my_file.read()
content = content.split()
print(f'количество слов - {len(content)}')
my_file.close()